--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/pheonix/Pictures/landscape-illustration.jpg"

-- Special
background="#181b33"
foreground="#cedce1"
cursor="#cedce1"

-- Colors
color0="#181b33"
color1="#C37C83"
color2="#AA8D90"
color3="#E0A99C"
color4="#F3D0B5"
color5="#92B4CD"
color6="#9FC0D3"
color7="#cedce1"
color8="#909a9d"
color9="#C37C83"
color10="#AA8D90"
color11="#E0A99C"
color12="#F3D0B5"
color13="#92B4CD"
color14="#9FC0D3"
color15="#cedce1"
