# Shell variables
# Generated by 'wal'
wallpaper='/home/pheonix/Pictures/landscape-illustration.jpg'

# Special
background='#181b33'
foreground='#cedce1'
cursor='#cedce1'

# Colors
color0='#181b33'
color1='#C37C83'
color2='#AA8D90'
color3='#E0A99C'
color4='#F3D0B5'
color5='#92B4CD'
color6='#9FC0D3'
color7='#cedce1'
color8='#909a9d'
color9='#C37C83'
color10='#AA8D90'
color11='#E0A99C'
color12='#F3D0B5'
color13='#92B4CD'
color14='#9FC0D3'
color15='#cedce1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
